---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mongodb
  labels:
    app: mongodb
    type: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        type: database
    spec:
      containers:
        - name: mongodb
          image: mongodb:3.6.19-xenial
          ports:
            containerPort: 27017
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MYSQL_ROOT_PASSWORD
