---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mongodb-app
  namespace: mongodb
spec:
  type: Git
  pathname: https://github.com/affian/rhacm_test_app.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: mongodb
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      clusterID: 3deeaf3a-b827-46d3-ae83-8963a2393262
status:
  decisions:
    - clusterName: dc01-power-ocp-01
      clusterNamespace: dc01-power-ocp-01
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mongodb-app
  namespace: mongodb
  labels:
    app: mongodb-app
  annotations:
    apps.open-cluster-management.io/github-path: https://github.com/affian/rhacm_test_app/tree/main/mongodb_resources
spec:
  channel: mongodb/mongodb-app
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
  secondaryChannel: ''
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mongodb-app
  namespace: mongodb
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mongodb-app
